"""Add counterparty_href field to Supply model

Revision ID: afe1c8a1255d
Revises: 
Create Date: 2025-01-28 12:35:02.612500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe1c8a1255d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_href', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('milk_mass', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fat_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fat_kg', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein_kg', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('store_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('protein_kg')
        batch_op.drop_column('fat_kg')
        batch_op.drop_column('protein_percent')
        batch_op.drop_column('fat_percent')
        batch_op.drop_column('milk_mass')
        batch_op.drop_column('counterparty_href')

    # ### end Alembic commands ###
